site_name: EIFFEL Ontology
site_description: 'EIFFEL Ontology Tools Documentation Hub'
site_author: 'Benjamin Molina'

# this allows visualizing content in github as anonympus user without having to log in
edit_uri: blob/master/docs/

theme: readthedocs

# we will use the same style as for the general PIXEL documentation hub (based on FIWARE and a readthedocs theme)
extra_css:
    - css/eiffel_a.css
    - css/eiffel_b.css
    - css/monokai_sublime_.css
    - css/pigments-monokai.css

repo_url: https://github.com/benmomo/eiffel-ontology-doc

nav:
    - Home: index.md
    - Semantics in EO: geoss.md
    - Ontologies used in EIFFEL: ontology.md
    - User Guide: user_guide.md


copyright: Apache License 2.0

extra:
  version: 1.0.0
  color: 26b3c3
